apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: gpu-scheduler
  name: keti-gpu-scheduler
  namespace: gpu
spec:
  selector:
    matchLabels:
      app: gpu-scheduler
  template:
    metadata:
      labels:
        app: gpu-scheduler
      name: gpu-scheduler
    spec:
      nodeName: master
      serviceAccountName: scheduler
      containers:
        - name: gpu-scheduler
          image: ketidevit2/gpu-scheduler:v2
          volumeMounts:
            - name: tz-config
              mountPath: /etc/localtime
            - name: gpu-scheduler-configmap
              mountPath: /tmp
          resources: 
            limits:
              memory: "200Mi"
            requests:
              memory: "200Mi"
      volumes:
        - name: tz-config
          hostPath:
            path: /usr/share/zoneinfo/Asia/Seoul
        - name: gpu-scheduler-configmap
          configMap:
            name: gpu-scheduler-configmap

            
