apiVersion: v1
kind: ConfigMap
metadata:
  name: gpu-scheduler-configmap
  namespace: gpu
data:
  node-gpu-score-weight : "0.3:0.7"
  nvlink-weight-percentage : "20"
  gpu-allocate-prefer : "binpack"
  node-reservation-permit : "false"
  pod-re-schedule-permit : "false"
  avoid-nvlink-one-gpu : "false"
  multi-node-allocation-permit : "false"
  non-gpu-node-prefer : "false"
  multi-gpu-node-prefer : "true"
  least-score-node-prefer : "true"
  avoid-high-score-node : "false"