apiVersion: v1
kind: ConfigMap
metadata:
  name: gpu-scheduler-policy
  namespace: gpu
data:
  node-gpu-score-weight : "0.3:0.7"
  nvlink-weight-percentage : "30"
  gpu-allocate-prefer : "spread"
  node-reservation-permit : "true"
  pod-re-schedule-permit : "true"
  avoid-nvlink-one-gpu : "true"
  multi-node-allocation-permit : "false"
  non-gpu-node-prefer : "false"
  multi-gpu-node-prefer : "false"
  least-score-node-prefer : "false"
  avoid-high-score-node : "false"