apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: gpu-scheduler
  name: keti-gpu-scheduler
  namespace: gpu
spec:
  selector:
    matchLabels:
      app: gpu-scheduler
  template:
    metadata:
      labels:
        app: gpu-scheduler
      name: gpu-scheduler
    spec:
      nodeName: c1-master
      serviceAccountName: scheduler
      imagePullSecrets:
        - name: regcred
      restartPolicy: Always
      containers:
        - name: gpu-schedule
          image: ketidevit2/keti-gpu-scheduler:v2.0
          # args:
          #   - --debugging=on
          volumeMounts:
            - name: tz-config
              mountPath: /etc/localtime
            - name: gpu-scheduler-policy
              mountPath: /gpu-scheduler-policy
            - name: config
              mountPath: /root/.kube/  
          resources:
            limits:
              memory: "200Mi"
            requests:
              memory: "200Mi"
          env:
          - name: DEBUGG_LEVEL
            value: "LEVEL1"
      volumes:
        - name: tz-config
          hostPath:
            path: /usr/share/zoneinfo/Asia/Seoul
        - name: gpu-scheduler-policy
          configMap:
            name: gpu-scheduler-policy
        - name: config
          hostPath:
            path: /root/.kube