apiVersion: batch/v1
kind: Job
metadata:
  name: nbody-benchmark-mps-test
  namespace: userpod
  annotations: 
    clusterName: gpu1
spec:
  template:
    spec:
      hostIPC: true
      schedulerName: gpu-scheduler
      containers:
        - image: seedjeffwan/nbody:cuda-10.1
          name: nbody1
          args:
            - nbody
            - -benchmark
            - -numdevices=1
            - -numbodies=1982000
          resources:
            limits:
              keti.com/mpsgpu: 1
              cpu: "250m"
              memory: "6400Mi"
            requests:
              cpu: "250m"
          volumeMounts:
            - name: nvidia-mps
              mountPath: /tmp/nvidia-mps 
      volumes:
        - name: nvidia-mps
          hostPath:
            path: /tmp/nvidia-mps
      restartPolicy: Never
