apiVersion: v1
kind: ServiceAccount
metadata:
  name: scheduler
  namespace: gpu
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: scheduler
  namespace: gpu
subjects:
- kind: ServiceAccount
  name: scheduler
  namespace: gpu
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: gpu-scheduler
  name: gpu-scheduler
  namespace: gpu
spec:
  selector:
    matchLabels:
      app: gpu-scheduler
  template:
    metadata:
      labels:
        app: gpu-scheduler
      name: gpu-scheduler
    spec:
      nodeName: master
      serviceAccountName: scheduler
      containers:
        - name: gpu-scheduler
          image: ketidevit/gpu-scheduler:v0.1
          volumeMounts:
            - name: tz-config
              mountPath: /etc/localtime
            - name: gpu-scheduler-configmap
              mountPath: /tmp
          resources: 
            limits:
              memory: "200Mi"
            requests:
              memory: "200Mi"
      volumes:
        - name: tz-config
          hostPath:
            path: /usr/share/zoneinfo/Asia/Seoul
        - name: gpu-scheduler-configmap
          configMap:
            name: gpu-scheduler-configmap
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: gpu-scheduler-configmap
  namespace: gpu
data:
  node-gpu-score-weight : "0.3 0.7"
  pod-re-schedule-permit : "true"
            
