apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx
  name: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
      name: nginx
    spec:
      schedulerName: gpu-scheduler
      containers:
        - name: nginx
          image: "nginx:1.11.1-alpine"
          ports:
          - containerPort: 80
          resources:
            limits:
              keti.com/mpsgpu: 1
            requests:
              cpu: "1250m"
              memory: "1280M"
          volumeMounts:
           - name: nvidia-mps
             mountPath: /tmp/nvidia-mps
      volumes:
       - name: nvidia-mps
         hostPath:
          path: /tmp/nvidia-mps
