apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx
  name: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
      name: nginx
    spec:
      containers:
        - name: nginx
          image: "nginx:1.11.1-alpine"
          ports:
          - containerPort: 80
          resources:
            requests:
              cpu: "125m"
              memory: "128M"
