// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.22.2
// source: proto/score/score.proto

package score

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Request) Reset() {
	*x = Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_score_score_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request) ProtoMessage() {}

func (x *Request) ProtoReflect() protoreflect.Message {
	mi := &file_proto_score_score_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request.ProtoReflect.Descriptor instead.
func (*Request) Descriptor() ([]byte, []int) {
	return file_proto_score_score_proto_rawDescGZIP(), []int{0}
}

type AnalysisScore struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Scores map[string]*NodeScore `protobuf:"bytes,1,rep,name=scores,proto3" json:"scores,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *AnalysisScore) Reset() {
	*x = AnalysisScore{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_score_score_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AnalysisScore) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalysisScore) ProtoMessage() {}

func (x *AnalysisScore) ProtoReflect() protoreflect.Message {
	mi := &file_proto_score_score_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalysisScore.ProtoReflect.Descriptor instead.
func (*AnalysisScore) Descriptor() ([]byte, []int) {
	return file_proto_score_score_proto_rawDescGZIP(), []int{1}
}

func (x *AnalysisScore) GetScores() map[string]*NodeScore {
	if x != nil {
		return x.Scores
	}
	return nil
}

type NodeScore struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NodeScore float32              `protobuf:"fixed32,1,opt,name=node_score,json=nodeScore,proto3" json:"node_score,omitempty"`
	GpuScores map[string]*GPUScore `protobuf:"bytes,2,rep,name=gpu_scores,json=gpuScores,proto3" json:"gpu_scores,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *NodeScore) Reset() {
	*x = NodeScore{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_score_score_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NodeScore) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeScore) ProtoMessage() {}

func (x *NodeScore) ProtoReflect() protoreflect.Message {
	mi := &file_proto_score_score_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeScore.ProtoReflect.Descriptor instead.
func (*NodeScore) Descriptor() ([]byte, []int) {
	return file_proto_score_score_proto_rawDescGZIP(), []int{2}
}

func (x *NodeScore) GetNodeScore() float32 {
	if x != nil {
		return x.NodeScore
	}
	return 0
}

func (x *NodeScore) GetGpuScores() map[string]*GPUScore {
	if x != nil {
		return x.GpuScores
	}
	return nil
}

type GPUScore struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GpuScore float32 `protobuf:"fixed32,1,opt,name=gpu_score,json=gpuScore,proto3" json:"gpu_score,omitempty"`
}

func (x *GPUScore) Reset() {
	*x = GPUScore{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_score_score_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GPUScore) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GPUScore) ProtoMessage() {}

func (x *GPUScore) ProtoReflect() protoreflect.Message {
	mi := &file_proto_score_score_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GPUScore.ProtoReflect.Descriptor instead.
func (*GPUScore) Descriptor() ([]byte, []int) {
	return file_proto_score_score_proto_rawDescGZIP(), []int{3}
}

func (x *GPUScore) GetGpuScore() float32 {
	if x != nil {
		return x.GpuScore
	}
	return 0
}

var File_proto_score_score_proto protoreflect.FileDescriptor

var file_proto_score_score_proto_rawDesc = []byte{
	0x0a, 0x17, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x73, 0x63, 0x6f, 0x72, 0x65, 0x2f, 0x73, 0x63,
	0x6f, 0x72, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x73, 0x63, 0x6f, 0x72, 0x65,
	0x22, 0x09, 0x0a, 0x07, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x96, 0x01, 0x0a, 0x0d,
	0x41, 0x6e, 0x61, 0x6c, 0x79, 0x73, 0x69, 0x73, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x12, 0x38, 0x0a,
	0x06, 0x73, 0x63, 0x6f, 0x72, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x20, 0x2e,
	0x73, 0x63, 0x6f, 0x72, 0x65, 0x2e, 0x41, 0x6e, 0x61, 0x6c, 0x79, 0x73, 0x69, 0x73, 0x53, 0x63,
	0x6f, 0x72, 0x65, 0x2e, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52,
	0x06, 0x73, 0x63, 0x6f, 0x72, 0x65, 0x73, 0x1a, 0x4b, 0x0a, 0x0b, 0x53, 0x63, 0x6f, 0x72, 0x65,
	0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x26, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x73, 0x63, 0x6f, 0x72, 0x65, 0x2e,
	0x4e, 0x6f, 0x64, 0x65, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65,
	0x3a, 0x02, 0x38, 0x01, 0x22, 0xb9, 0x01, 0x0a, 0x09, 0x4e, 0x6f, 0x64, 0x65, 0x53, 0x63, 0x6f,
	0x72, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x6e, 0x6f, 0x64, 0x65, 0x5f, 0x73, 0x63, 0x6f, 0x72, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x02, 0x52, 0x09, 0x6e, 0x6f, 0x64, 0x65, 0x53, 0x63, 0x6f, 0x72,
	0x65, 0x12, 0x3e, 0x0a, 0x0a, 0x67, 0x70, 0x75, 0x5f, 0x73, 0x63, 0x6f, 0x72, 0x65, 0x73, 0x18,
	0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x73, 0x63, 0x6f, 0x72, 0x65, 0x2e, 0x4e, 0x6f,
	0x64, 0x65, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x2e, 0x47, 0x70, 0x75, 0x53, 0x63, 0x6f, 0x72, 0x65,
	0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x09, 0x67, 0x70, 0x75, 0x53, 0x63, 0x6f, 0x72, 0x65,
	0x73, 0x1a, 0x4d, 0x0a, 0x0e, 0x47, 0x70, 0x75, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x73, 0x45, 0x6e,
	0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x25, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x73, 0x63, 0x6f, 0x72, 0x65, 0x2e, 0x47, 0x50, 0x55,
	0x53, 0x63, 0x6f, 0x72, 0x65, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01,
	0x22, 0x27, 0x0a, 0x08, 0x47, 0x50, 0x55, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x12, 0x1b, 0x0a, 0x09,
	0x67, 0x70, 0x75, 0x5f, 0x73, 0x63, 0x6f, 0x72, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x02, 0x52,
	0x08, 0x67, 0x70, 0x75, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x32, 0x3e, 0x0a, 0x0a, 0x4d, 0x65, 0x74,
	0x72, 0x69, 0x63, 0x47, 0x52, 0x50, 0x43, 0x12, 0x30, 0x0a, 0x08, 0x47, 0x65, 0x74, 0x53, 0x63,
	0x6f, 0x72, 0x65, 0x12, 0x0e, 0x2e, 0x73, 0x63, 0x6f, 0x72, 0x65, 0x2e, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x14, 0x2e, 0x73, 0x63, 0x6f, 0x72, 0x65, 0x2e, 0x41, 0x6e, 0x61, 0x6c,
	0x79, 0x73, 0x69, 0x73, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x42, 0x19, 0x5a, 0x17, 0x67, 0x72, 0x70,
	0x63, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x73,
	0x63, 0x6f, 0x72, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_score_score_proto_rawDescOnce sync.Once
	file_proto_score_score_proto_rawDescData = file_proto_score_score_proto_rawDesc
)

func file_proto_score_score_proto_rawDescGZIP() []byte {
	file_proto_score_score_proto_rawDescOnce.Do(func() {
		file_proto_score_score_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_score_score_proto_rawDescData)
	})
	return file_proto_score_score_proto_rawDescData
}

var file_proto_score_score_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_score_score_proto_goTypes = []interface{}{
	(*Request)(nil),       // 0: score.Request
	(*AnalysisScore)(nil), // 1: score.AnalysisScore
	(*NodeScore)(nil),     // 2: score.NodeScore
	(*GPUScore)(nil),      // 3: score.GPUScore
	nil,                   // 4: score.AnalysisScore.ScoresEntry
	nil,                   // 5: score.NodeScore.GpuScoresEntry
}
var file_proto_score_score_proto_depIdxs = []int32{
	4, // 0: score.AnalysisScore.scores:type_name -> score.AnalysisScore.ScoresEntry
	5, // 1: score.NodeScore.gpu_scores:type_name -> score.NodeScore.GpuScoresEntry
	2, // 2: score.AnalysisScore.ScoresEntry.value:type_name -> score.NodeScore
	3, // 3: score.NodeScore.GpuScoresEntry.value:type_name -> score.GPUScore
	0, // 4: score.MetricGRPC.GetScore:input_type -> score.Request
	1, // 5: score.MetricGRPC.GetScore:output_type -> score.AnalysisScore
	5, // [5:6] is the sub-list for method output_type
	4, // [4:5] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_proto_score_score_proto_init() }
func file_proto_score_score_proto_init() {
	if File_proto_score_score_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_score_score_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_score_score_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AnalysisScore); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_score_score_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NodeScore); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_score_score_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GPUScore); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_score_score_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_score_score_proto_goTypes,
		DependencyIndexes: file_proto_score_score_proto_depIdxs,
		MessageInfos:      file_proto_score_score_proto_msgTypes,
	}.Build()
	File_proto_score_score_proto = out.File
	file_proto_score_score_proto_rawDesc = nil
	file_proto_score_score_proto_goTypes = nil
	file_proto_score_score_proto_depIdxs = nil
}
